AWSTemplateFormatVersion: 2010-09-09
Description: Aws-Study-ApplicationLayer

Parameters:
  DBMasterUsername:
    Type: String
    Default: admin
    Description: Master username for the RDS instance
  AMI:
    Type: AWS::EC2::Image::Id
    Description: AMI ID to use for the EC2 instance
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of the key pair to use for the EC2 instance

Resources:
# Create Application Load Balancer
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: AwsStudyALB
      Subnets:
        - !ImportValue PublicSubnet1aId
        - !ImportValue PublicSubnet1cId
      SecurityGroups:
        - !ImportValue AlbSecurityGroupId
      Scheme: internet-facing
      Type: application
# Create ALB Listener
  AlbListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref AlbTargetGroup
# Create ALB Target Group
  AlbTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: AwsStudyTargetGroup
      Protocol: HTTP
      Port: 8080
      VpcId: !ImportValue AwsStudyVpcId
      TargetType: instance  
      HealthCheckProtocol: HTTP
      HealthCheckPath: /
      HealthCheckIntervalSeconds: 30
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 3
      Matcher:
        HttpCode: 200
      Targets: 
        - Id: !Ref Ec2Instance
          Port: 8080
      Tags:
        - Key: Name
          Value: AwsStudyAlb
# Create EC2 Instance
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AMI
      InstanceType: t3.micro
      KeyName: !Ref KeyName
      NetworkInterfaces:
      - DeviceIndex: 0
        AssociatePublicIpAddress: true
        SubnetId: !ImportValue PublicSubnet1aId
        GroupSet:
          - !ImportValue Ec2SecurityGroupId
        DeleteOnTermination: true
      Tags:
        - Key: Name
          Value: AwsStudyEC2
# Create RDS (MySQL)
  MyRDS:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    UpdateReplacePolicy: Snapshot
    Properties:
      DBInstanceIdentifier: aws-study-db
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      Engine: mysql
      MasterUsername: !Ref DBMasterUsername
      MasterUserPassword: '{{resolve:ssm-secure:/rds/master/password}}'
      DBSubnetGroupName: !Ref RdsSubnetGroup
      VPCSecurityGroups:
        - !ImportValue RdsSecurityGroupId
      BackupRetentionPeriod: 7
      PubliclyAccessible: false
      MultiAZ: false
      Tags:
        - Key: Name
          Value: AwsStudyRDS
# Create RDS Subnet Group
  RdsSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnets for RDS
      SubnetIds:
        - !ImportValue PrivateSubnet1aId
        - !ImportValue PrivateSubnet1cId
      DBSubnetGroupName: Aws-Study-Dbsubnet
