AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation execution role for all stacks

Resources:
  CloudFormationExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CloudFormationExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CloudFormationExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              # ---- Basic resource operation permissions ----
              - Effect: Allow
                Action:
                  - ec2:*
                  - s3:*
                  - rds:*
                  - elasticloadbalancing:*
                  - iam:PassRole
                Resource: "*"
              # ---- Permission to access SSM parameters ----
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParameters
                Resource: !Sub arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/rds/master/password
              # ---- Permission to decrypt (KMS) ----
              - Effect: Allow
                Action:
                  - kms:Decrypt
                Resource: !Sub arn:${AWS::Partition}:kms:${AWS::Region}:${AWS::AccountId}:key/*
