AWSTemplateFormatVersion: "2010-09-09"
Description: Aws-Study-SecurityLayer
#MyIp
Parameters:
  CidrIpFromInternet:
    Type: String
    Description: CIDR IP range for allowing access from the internet
    Default: 36.8.0.45/32

Resources:
#ALBSecurityGroup
  AlbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP/HTTPS from the Internet
      VpcId: !ImportValue AwsStudyVpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: AlbSecurityGroup
#EC2SecurityGroup
  Ec2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow traffic from ALB
      VpcId: !ImportValue AwsStudyVpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          SourceSecurityGroupId: !Ref AlbSecurityGroup
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref CidrIpFromInternet
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0  
      Tags:
        - Key: Name
          Value: Ec2SecurityGroup
#RdsSecurityGroup:
  RdsSecurityGroup:
    Type: AWS::EC2::SecurityGroup 
    Properties:
      GroupDescription: Allow DB access from EC2
      VpcId: !ImportValue AwsStudyVpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref Ec2SecurityGroup
      Tags:
        - Key: Name
          Value: RdsSecurityGroup

Outputs:
  AlbSecurityGroupId:
    Value: !Ref AlbSecurityGroup
    Export:
      Name: AlbSecurityGroupId
  Ec2SecurityGroupId:
    Value: !Ref Ec2SecurityGroup
    Export:
      Name: Ec2SecurityGroupId
  RdsSecurityGroupId:
    Value: !Ref RdsSecurityGroup
    Export:
      Name: RdsSecurityGroupId
