AWSTemplateFormatVersion: 2010-09-09
Description: Aws-Study-SecurityLayer

Resources:

  # ALB Security Group
  AwsStudyAlbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP/HTTPS from Internet
      VpcId: !ImportValue AwsStudyVpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: AwsStudyAlbSecurityGroup
        - Key: Project
          Value: AwsStudy

  # EC2 Security Group
  AwsStudyEc2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow traffic from ALB + SSH from My IP
      VpcId: !ImportValue AwsStudyVpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          SourceSecurityGroupId: !Ref AwsStudyAlbSecurityGroup
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: AwsStudyEc2SecurityGroup
        - Key: Project
          Value: AwsStudy

  # Security Group for SSM VPC Endpoints
  AwsStudySsmEndpointSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTPS from EC2 to SSM VPC endpoints
      VpcId: !ImportValue AwsStudyVpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          SourceSecurityGroupId: !Ref AwsStudyEc2SecurityGroup
      Tags:
        - Key: Name
          Value: AwsStudySsmEndpointSecurityGroup
        - Key: Project
          Value: AwsStudy

  # RDS Security Group
  AwsStudyRdsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow DB access from EC2
      VpcId: !ImportValue AwsStudyVpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref AwsStudyEc2SecurityGroup
      Tags:
        - Key: Name
          Value: AwsStudyRdsSecurityGroup
        - Key: Project
          Value: AwsStudy

Outputs:
  AlbSecurityGroupId:
    Value: !Ref AwsStudyAlbSecurityGroup
    Export:
      Name: AwsStudyAlbSecurityGroupId

  Ec2SecurityGroupId:
    Value: !Ref AwsStudyEc2SecurityGroup
    Export:
      Name: AwsStudyEc2SecurityGroupId

  RdsSecurityGroupId:
    Value: !Ref AwsStudyRdsSecurityGroup
    Export:
      Name: AwsStudyRdsSecurityGroupId

  AwsStudySsmEndpointSecurityGroupId:
    Description: Security Group ID for SSM VPC endpoints
    Value: !Ref AwsStudySsmEndpointSecurityGroup
    Export:
      Name: AwsStudySsmEndpointSecurityGroupId
